version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: cephasgm_vpn_mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cephasgm_vpn
    networks:
      - vpn-network

  # VPN API Server
  vpn-api:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: cephasgm_vpn_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://mongodb:27017/cephasgm_vpn
      - JWT_SECRET=${JWT_SECRET}
      - WIREGUARD_PORT=${WIREGUARD_PORT}
    volumes:
      - ../configs:/app/configs
      - ../logs/api:/app/logs
    depends_on:
      - mongodb
    networks:
      - vpn-network

  # Admin Dashboard
  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    container_name: cephasgm_vpn_dashboard
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - API_URL=http://vpn-api:3000
      - PORT=3001
    depends_on:
      - vpn-api
    networks:
      - vpn-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: cephasgm_vpn_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - vpn-api
      - dashboard
    networks:
      - vpn-network

volumes:
  mongodb_data:

networks:
  vpn-network:
    driver: bridge